function [dati] = F_dati(testname)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% inserire qui i dati iniziali necessari a far partire un test %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if (strcmp(testname, 'test1'))
    % test1: area function uguale a 1 e non dipendendte dal tempo, non c'è
    % dissipation
    dati = struct('name',      testname, ...
        ... %name
        'length',               0.19, ...
        ... %lunghezza del tratto vocale [m]
        'n',                    2^4, ...
        ... %numero di punti in cui dividere la lunghezza
        'fs',                   44100, ...
        ... %sempling frequncy [Hz]
        'dt',                   1/44100, ...
        ... %time stepsize [s]
        'A',                    '0.1 + 0.*x', ...
        ... %area function [m^2]
        'T',                    1, ...
        ... %durata della simulazione [s]
        'c',                    343 ...
        );
end

if (strcmp(testname, 'test2'))
    dati = struct('name',      testname, ...
        ... %name
        'length',               0.19, ...
        ... %lunghezza del tratto vocale [m]
        'n',                    19, ...
        ... %numero di punti in cui dividere la lunghezza
        'fs',                   44100, ...
        ... %sempling frequncy [Hz]
        'dt',                   1/44100, ...
        ... %time stepsize [s]
        'A',                    'bsxfun(@plus, 0.*t ,0.1 + 0.*x)', ...
        ... %area function [m^2]
        'T',                    2, ...
        ... %durata della simulazione [s]
        'c',                    343, ...
        'fGP',                  100, ...
        ... %frequenza del glottal pulse, determina il tono della voce stessa
        't0',                  1/100, ...
        ... %tempo di un impulso
        't1',                   0.003, ...
        ... %punto di picco del glottal pulse
        't2',                   0.005, ...
        ... %istante in cui il glottal pulse torna a 0
        'Ag',                   0.08 ...
        ... %ampiezza picco del glottal pulse 
        );
end





end